### ISSUE TITLE
Macromolecule properties should include extinction coefficient

### ISSUE THREAD

**Issue by ClairePA** [tony-yuan/JsHELM#22]
The coefficient calculation should be performed via the toolkit web service.

**Comment by tony-yuan** [comment]
We need the online HelmToolkitWS to support GET to avoid cross-domain issue:

"Is it possible to modify the RESTful web service to accept QueryString (GET) as well?  Because of cross-domain issue, other web applications cannot POST data to your domain.
http://46.101.131.62:8080/WebService/service/Calculation/MoleculeProperties "

**Comment by tony-yuan** [comment]
Tianhong's comments on how to enable CORS:
------------------
I added the following to the web.xml file for HELM2WebService, which enables CORS for all services, including POST:
```
<filter>
<filter-name>CorsFilter</filter-name>
<filter-class>org.apache.catalina.filters.CorsFilter</filter-class>
</filter>
<filter-mapping>
<filter-name>CorsFilter</filter-name>
<url-pattern>/*</url-pattern>	
</filter-mapping>

```

**Comment by tony-yuan** [comment]
Extinction Coefficient is implemented in the javascript side in 2016-09-23 udpate

**Comment by ClairePA** [comment]
Confirmed fixed. Close.
