### ISSUE TITLE
HELM strings are case sensitive 

### ISSUE THREAD

**Issue by ypotier** [tony-yuan/JsHELM#82]
When loading sequences with monomer in upper case, I have an error message on the canvas that the monomer is not recognized.
For example: RNA1{R(A)P.R(U)P.R(C)P.R(G)}$$$$V2.0
the monomer R is not accepted.

This sequence was generated with the HELM toolkit so it should be accepted.
@ClairePA please confirm .

**Comment by ClairePA** [comment]
HELM strings including monomer definitions are case sensitive. I think the problem here is that the toolkit and the editor are using different monomer sets. The editor denotes ribose as r since it is using the Ionis set and the toolkit as R which was in the original set.

I will ask Markus if it is a lot of work to point the toolkit to the Ionis public monomer set.

**Comment by ypotier** [comment]
Thank you, I could not remember if there had been a decision on case sensitivity.
I actually think that might be interesting to raise again because it will be confusing.

**Comment by ClairePA** [comment]
Monomer set consistency being addressed elsewhere. This particular issue should be closed.
